### ISSUE TITLE
Cascading delete associations without Trash behavior

### ISSUE THREAD

**Issue by michielkeijts** [UseMuffin/Trash#35]
At the moment it seems not possible to delete associations (HasOne, HasMany) from a Table with Trash behavior. As it is in the Trashbehavior Class: `_isRecursable()`, the behavior of the association is checked:
`$association->target()->hasBehavior('Trash')`

If this is not the case, FALSE is returned and cascadeDelete is not called.

However, I wonder if this is the desired behavior? Or, if it is, it should possibly be noted in the Readme.

In my setup, I have various models not using this behavior, but are related to a Trashable behavior enabled model.

What do you think? Should it stay like this, or should the associated Table not necessarily have the Trash behavior to execute a cascadeDelete?

**Comment by davidyell** [comment]
I wrote that behaviour. To me it makes sense to only cascade through tables which implement the behaviour. This is for a number of reasons. 

The first being that a cascading delete is a dangerous process, and allowing it to cascade across tables which both do and do not implement the behaviour would mean that you soft delete some data and actually delete other data, which provides an inconsistent outcome to "I want to soft delete these things". Can you imagine losing your database data because you didn't realise? 😬 

The other one is that once that data is gone, it's gone. That's not really what a behaviour called Soft Delete should be doing in my opinion. It's outside of the plugins scope in my mind. You want to soft delete some stuff and delete other stuff, you should be writing that code yourself so you know what the expected behaviour is.

Perhaps a compromise could be that if the Trashable behaviour is not attached to the table class, it could just skip that table and keep processing the association tree to find more table classes with the behaviour attached. However this could lead to data quality issues where you have items which are not deleted being associated to deleted items. This would break queries and templates as soft deleted data would not be returned when querying.

**Comment by ADmad** [comment]
> The first being that a cascading delete is a dangerous process, and allowing it to cascade across tables which both do and do not implement the behaviour would mean that you soft delete some data and actually delete other data, which provides an inconsistent outcome to "I want to soft delete these things". Can you imagine losing your database data because you didn't realise?

Exactly, such a dangerous behavior isn't going to be supported.

> Perhaps a compromise could be that if the Trashable behaviour is not attached to the table class, it could just skip that table and keep processing the association tree to find more table classes with the behaviour attached. However this could lead to data quality issues where you have items which are not deleted being associated to deleted items. This would break queries and templates as soft deleted data would not be returned when querying.

Yup these could lead of issues and non intuitive behavior, so not really an option either.

If someone feels this needs clarification in readme a PR is welcome.
